#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ] # USER MUST BE ROOT

### PULL DATA ###
rm -rf "${constentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$constents_owner/$constents"
chown www-data:www-data "$constentsdir" -R

